### ISSUE TITLE
Theme Mixer - Decorations

### ISSUE THREAD

**Issue by originalfoo** [TheCSUser/HideItBobby#2]
The [Theme Mixer](https://steamcommunity.com/sharedfiles/filedetails/?id=1899640536) mod (id: 1899640536) has settings to show/hide decorations (cliff, fertile, grass), as illustrated on the screenshot below:

![image](https://user-images.githubusercontent.com/1386719/143660821-26a87175-cf0b-474d-b128-94a679ce1c65.png)

As Theme Mixer allows sharing theme mixes to the workshop, and creating / selecting mixes in-game, it is probably better to let it control decorations if the user has it active.

Related code: https://github.com/TheCSUser/HideItBobby/tree/master/Features/Decorations

**Comment by TheCSUser** [comment]
Implemented in 1.32

**Comment by originalfoo** [comment]
Works perfectly - thanks!!
